[2025-09-23T20:53:11.883+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T20:53:11.914+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wine_pipeline.stage3_deploy_compose scheduled__2025-09-23T20:45:00+00:00 [queued]>
[2025-09-23T20:53:11.927+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wine_pipeline.stage3_deploy_compose scheduled__2025-09-23T20:45:00+00:00 [queued]>
[2025-09-23T20:53:11.928+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2025-09-23T20:53:11.945+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): stage3_deploy_compose> on 2025-09-23 20:45:00+00:00
[2025-09-23T20:53:11.954+0000] {standard_task_runner.py:72} INFO - Started process 575 to run task
[2025-09-23T20:53:11.958+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'wine_pipeline', 'stage3_deploy_compose', 'scheduled__2025-09-23T20:45:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/wine_pipeline.py', '--cfg-path', '/tmp/tmps24vvyf2']
[2025-09-23T20:53:11.962+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask stage3_deploy_compose
[2025-09-23T20:53:12.035+0000] {task_command.py:467} INFO - Running <TaskInstance: wine_pipeline.stage3_deploy_compose scheduled__2025-09-23T20:45:00+00:00 [running]> on host a72da1fa20c9
[2025-09-23T20:53:12.145+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wine_pipeline' AIRFLOW_CTX_TASK_ID='stage3_deploy_compose' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T20:45:00+00:00'
[2025-09-23T20:53:12.147+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-23T20:53:12.163+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-23T20:53:12.164+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker compose -f /opt/***/code/deployment/docker-compose.yml up -d --build']
[2025-09-23T20:53:12.178+0000] {subprocess.py:99} INFO - Output:
[2025-09-23T20:53:12.310+0000] {subprocess.py:106} INFO - time="2025-09-23T20:53:12Z" level=warning msg="/opt/***/code/deployment/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
[2025-09-23T20:53:12.354+0000] {subprocess.py:106} INFO - time="2025-09-23T20:53:12Z" level=warning msg="Docker Compose is configured to build using Bake, but buildx isn't installed"
[2025-09-23T20:53:12.640+0000] {subprocess.py:106} INFO - #0 building with "default" instance using docker driver
[2025-09-23T20:53:12.641+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:12.642+0000] {subprocess.py:106} INFO - #1 [api internal] load build definition from Dockerfile
[2025-09-23T20:53:12.642+0000] {subprocess.py:106} INFO - #1 transferring dockerfile: 264B done
[2025-09-23T20:53:12.643+0000] {subprocess.py:106} INFO - #1 DONE 0.0s
[2025-09-23T20:53:12.644+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:12.644+0000] {subprocess.py:106} INFO - #2 [api internal] load metadata for docker.io/library/python:3.10-slim
[2025-09-23T20:53:13.208+0000] {subprocess.py:106} INFO - #2 DONE 0.7s
[2025-09-23T20:53:13.328+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.329+0000] {subprocess.py:106} INFO - #3 [api internal] load .dockerignore
[2025-09-23T20:53:13.329+0000] {subprocess.py:106} INFO - #3 transferring context: 2B done
[2025-09-23T20:53:13.330+0000] {subprocess.py:106} INFO - #3 DONE 0.0s
[2025-09-23T20:53:13.334+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.334+0000] {subprocess.py:106} INFO - #4 [api internal] load build context
[2025-09-23T20:53:13.335+0000] {subprocess.py:106} INFO - #4 transferring context: 64B done
[2025-09-23T20:53:13.336+0000] {subprocess.py:106} INFO - #4 DONE 0.0s
[2025-09-23T20:53:13.337+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.339+0000] {subprocess.py:106} INFO - #5 [api 1/5] FROM docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730
[2025-09-23T20:53:13.343+0000] {subprocess.py:106} INFO - #5 resolve docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730 0.0s done
[2025-09-23T20:53:13.345+0000] {subprocess.py:106} INFO - #5 DONE 0.0s
[2025-09-23T20:53:13.349+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.350+0000] {subprocess.py:106} INFO - #6 [api 4/5] RUN pip install --no-cache-dir -r requirements.txt
[2025-09-23T20:53:13.350+0000] {subprocess.py:106} INFO - #6 CACHED
[2025-09-23T20:53:13.351+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.352+0000] {subprocess.py:106} INFO - #7 [api 2/5] WORKDIR /app
[2025-09-23T20:53:13.355+0000] {subprocess.py:106} INFO - #7 CACHED
[2025-09-23T20:53:13.355+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.356+0000] {subprocess.py:106} INFO - #8 [api 3/5] COPY requirements.txt .
[2025-09-23T20:53:13.360+0000] {subprocess.py:106} INFO - #8 CACHED
[2025-09-23T20:53:13.363+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.364+0000] {subprocess.py:106} INFO - #9 [api 5/5] COPY main.py .
[2025-09-23T20:53:13.365+0000] {subprocess.py:106} INFO - #9 CACHED
[2025-09-23T20:53:13.368+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.372+0000] {subprocess.py:106} INFO - #10 [api] exporting to image
[2025-09-23T20:53:13.373+0000] {subprocess.py:106} INFO - #10 exporting layers done
[2025-09-23T20:53:13.374+0000] {subprocess.py:106} INFO - #10 exporting manifest sha256:1181bbbf188104c9b72cb7a4b2576a16324961a8a400b6cbb89476beb8892567 done
[2025-09-23T20:53:13.374+0000] {subprocess.py:106} INFO - #10 exporting config sha256:6aba02f92f2678889022da532e9cdcd4a3e3d2d98ebb364e58680ff23fa3269b done
[2025-09-23T20:53:13.375+0000] {subprocess.py:106} INFO - #10 exporting attestation manifest sha256:91ed0df44ac3436b844e82c89c908f944f13cbc2e409ea69f11a820e25d71389 0.0s done
[2025-09-23T20:53:13.376+0000] {subprocess.py:106} INFO - #10 exporting manifest list sha256:b7893382e6ad09e56951c7ce54d6c6f4068b8240a0d458c0a90bbeaeaf510b99
[2025-09-23T20:53:13.564+0000] {subprocess.py:106} INFO - #10 exporting manifest list sha256:b7893382e6ad09e56951c7ce54d6c6f4068b8240a0d458c0a90bbeaeaf510b99 0.0s done
[2025-09-23T20:53:13.565+0000] {subprocess.py:106} INFO - #10 naming to docker.io/library/wine-api:latest done
[2025-09-23T20:53:13.566+0000] {subprocess.py:106} INFO - #10 unpacking to docker.io/library/wine-api:latest 0.0s done
[2025-09-23T20:53:13.568+0000] {subprocess.py:106} INFO - #10 DONE 0.2s
[2025-09-23T20:53:13.570+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.574+0000] {subprocess.py:106} INFO - #11 [api] resolving provenance for metadata file
[2025-09-23T20:53:13.692+0000] {subprocess.py:106} INFO - #11 DONE 0.0s
[2025-09-23T20:53:13.888+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.889+0000] {subprocess.py:106} INFO - #12 [app internal] load build definition from Dockerfile
[2025-09-23T20:53:13.890+0000] {subprocess.py:106} INFO - #12 transferring dockerfile: 232B 0.0s done
[2025-09-23T20:53:13.890+0000] {subprocess.py:106} INFO - #12 DONE 0.0s
[2025-09-23T20:53:13.892+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:13.893+0000] {subprocess.py:106} INFO - #2 [app internal] load metadata for docker.io/library/python:3.10-slim
[2025-09-23T20:53:13.995+0000] {subprocess.py:106} INFO - #2 DONE 1.0s
[2025-09-23T20:53:14.118+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.119+0000] {subprocess.py:106} INFO - #13 [app internal] load .dockerignore
[2025-09-23T20:53:14.125+0000] {subprocess.py:106} INFO - #13 transferring context: 2B done
[2025-09-23T20:53:14.126+0000] {subprocess.py:106} INFO - #13 DONE 0.0s
[2025-09-23T20:53:14.127+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.128+0000] {subprocess.py:106} INFO - #14 [app internal] load build context
[2025-09-23T20:53:14.129+0000] {subprocess.py:106} INFO - #14 transferring context: 63B done
[2025-09-23T20:53:14.133+0000] {subprocess.py:106} INFO - #14 DONE 0.0s
[2025-09-23T20:53:14.134+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.136+0000] {subprocess.py:106} INFO - #5 [app 1/5] FROM docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730
[2025-09-23T20:53:14.137+0000] {subprocess.py:106} INFO - #5 resolve docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730 0.1s done
[2025-09-23T20:53:14.138+0000] {subprocess.py:106} INFO - #5 DONE 0.1s
[2025-09-23T20:53:14.261+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.265+0000] {subprocess.py:106} INFO - #15 [app 3/5] COPY requirements.txt .
[2025-09-23T20:53:14.266+0000] {subprocess.py:106} INFO - #15 CACHED
[2025-09-23T20:53:14.267+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.268+0000] {subprocess.py:106} INFO - #16 [app 4/5] RUN pip install --no-cache-dir -r requirements.txt
[2025-09-23T20:53:14.268+0000] {subprocess.py:106} INFO - #16 CACHED
[2025-09-23T20:53:14.269+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.270+0000] {subprocess.py:106} INFO - #7 [app 2/5] WORKDIR /app
[2025-09-23T20:53:14.272+0000] {subprocess.py:106} INFO - #7 CACHED
[2025-09-23T20:53:14.275+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.276+0000] {subprocess.py:106} INFO - #17 [app 5/5] COPY app.py .
[2025-09-23T20:53:14.283+0000] {subprocess.py:106} INFO - #17 CACHED
[2025-09-23T20:53:14.285+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.287+0000] {subprocess.py:106} INFO - #18 [app] exporting to image
[2025-09-23T20:53:14.288+0000] {subprocess.py:106} INFO - #18 exporting layers done
[2025-09-23T20:53:14.290+0000] {subprocess.py:106} INFO - #18 exporting manifest sha256:ed39c8a1281e8641f8221aa358161ed4a853cfca766b2391723ef213149408a1 done
[2025-09-23T20:53:14.291+0000] {subprocess.py:106} INFO - #18 exporting config sha256:6f0abffb2ffefdf85f78ba18149c8f66629e2f426c54fc38cab1a328af33f1f1 done
[2025-09-23T20:53:14.293+0000] {subprocess.py:106} INFO - #18 exporting attestation manifest sha256:953c59cd16f365e92bec385ff0a4855f80ad82c1254842854ceb5f4364f3eab8 0.0s done
[2025-09-23T20:53:14.295+0000] {subprocess.py:106} INFO - #18 exporting manifest list sha256:fc0624f700cb5564da1799083bac97fca8142d0156fed37694ca329607dbf4d5 0.0s done
[2025-09-23T20:53:14.297+0000] {subprocess.py:106} INFO - #18 naming to docker.io/library/wine-app:latest done
[2025-09-23T20:53:14.298+0000] {subprocess.py:106} INFO - #18 unpacking to docker.io/library/wine-app:latest 0.0s done
[2025-09-23T20:53:14.300+0000] {subprocess.py:106} INFO - #18 DONE 0.1s
[2025-09-23T20:53:14.379+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:53:14.381+0000] {subprocess.py:106} INFO - #19 [app] resolving provenance for metadata file
[2025-09-23T20:53:14.396+0000] {subprocess.py:106} INFO - #19 DONE 0.0s
[2025-09-23T20:53:14.398+0000] {subprocess.py:106} INFO -  api  Built
[2025-09-23T20:53:14.400+0000] {subprocess.py:106} INFO -  app  Built
[2025-09-23T20:53:14.431+0000] {subprocess.py:106} INFO -  Container wine-api-1  Recreate
[2025-09-23T20:53:14.763+0000] {subprocess.py:106} INFO -  Container wine-api-1  Recreated
[2025-09-23T20:53:14.765+0000] {subprocess.py:106} INFO -  Container wine-app-1  Recreate
[2025-09-23T20:53:15.274+0000] {subprocess.py:106} INFO -  Container wine-app-1  Recreated
[2025-09-23T20:53:15.331+0000] {subprocess.py:106} INFO -  Container wine-api-1  Starting
[2025-09-23T20:53:15.345+0000] {subprocess.py:106} INFO - Error response from daemon: mounts denied:
[2025-09-23T20:53:15.348+0000] {subprocess.py:106} INFO - The path /opt/***/models is not shared from the host and is not known to Docker.
[2025-09-23T20:53:15.349+0000] {subprocess.py:106} INFO - You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
[2025-09-23T20:53:15.351+0000] {subprocess.py:106} INFO - See https://docs.docker.com/go/mac-file-sharing/ for more info.
[2025-09-23T20:53:15.355+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-23T20:53:15.391+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/bash.py", line 232, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-23T20:53:15.419+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=wine_pipeline, task_id=stage3_deploy_compose, run_id=scheduled__2025-09-23T20:45:00+00:00, execution_date=20250923T204500, start_date=20250923T205311, end_date=20250923T205315
[2025-09-23T20:53:15.462+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-23T20:53:15.463+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 249 for task stage3_deploy_compose (Bash command failed. The command returned a non-zero exit code 1.; 575)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/bash.py", line 232, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-23T20:53:15.519+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-23T20:53:15.556+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T20:53:15.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
